### ISSUE TITLE
buf.write在nodejs -v 6版本以上新API会报错

### ISSUE THREAD

**Issue by SamZhou99** [play175/ByteBuffer#5]
255行，由于新版API改动报错。
//是否可以修改下
//node版本号大于等于6就，参数2和参数3，调换个位置。
(parseInt(process.versions.node)>=6) ? _org_buf.write(_list[i].d,offset,_encoding) : _org_buf.write(_list[i].d,_encoding,offset);

**Comment by SamZhou99** [comment]
你好，你可以在npm上更新一下吗？
因为每次 npm install 时都是你旧版的，因此报错需要手动更改:)

**Comment by play175** [comment]
不好意思，已经更新到NPM了
