### ISSUE TITLE
请教用nodejs实现反向代理远程桌面

### ISSUE THREAD

**Issue by antmail** [play175/ByteBuffer#6]
play175大神，在您的网站上看到了“用nodejs实现反向代理远程桌面”，但是现在googlecode已经不能下载了，能在github上上传吗？万分感谢，实在没有您的联络方式，只能在这里找您了

**Comment by play175** [comment]
你好，我在网站上增加了下载连接

**Comment by antmail** [comment]
谢谢您的帮助
